<?php
return array(
	'BE' => array(
		'compressionLevel' => 5,
		'debug' => FALSE,
		'explicitADmode' => 'explicitAllow',
		'fileCreateMask' => '0660',
		'fileDenyPattern' => '\\.(php[3-6]?|phpsh|phtml)(\\..*)?$|^\\.htaccess$',
		'folderCreateMask' => '2770',
		'installToolPassword' => 'Smokie - Who the fuck is Alice',
		'lockIP' => '4',
		'lockSSL' => '2',
		'loginSecurityLevel' => 'rsa',
		'noPHPscriptInclude' => '1',
		'sessionTimeout' => '36000',
		'warning_email_addr' => 'example@example.com',
	),
	'DB' => array(
		'database' => '',
		'host' => '',
		'password' => '',
		'port' => 3306,
		'username' => '',
	),
	'EXT' => array(
		'allowLocalInstall' => '0',
		'extConf' => array(
			'be_secure_pw' => 'a:7:{s:14:"passwordLength";s:1:"8";s:13:"lowercaseChar";s:1:"1";s:11:"capitalChar";s:1:"1";s:5:"digit";s:1:"1";s:11:"specialChar";s:1:"1";s:8:"patterns";s:1:"3";s:10:"validUntil";s:0:"";}',
			'css_styled_content' => 'a:2:{s:15:"setPageTSconfig";s:1:"1";s:19:"removePositionTypes";s:1:"1";}',
			'mktools' => 'a:13:{s:20:"contentReplaceActive";s:1:"0";s:25:"ajaxContentRendererActive";s:1:"0";s:20:"pageNotFoundHandling";s:1:"1";s:13:"realUrlXclass";s:1:"0";s:22:"seoRobotsMetaTagActive";s:1:"1";s:32:"shouldFalImagesBeAddedToCalEvent";s:1:"0";s:30:"shouldFalImagesBeAddedToTtNews";s:1:"0";s:13:"exceptionPage";s:26:"FILE:unavailable/index.php";s:22:"tableFixedPostVarTypes";s:1:"0";s:24:"realUrlConfigurationFile";s:0:"";s:28:"realUrlConfigurationTemplate";s:0:"";s:27:"tcaPostProcessingExtensions";s:0:"";s:22:"systemLogLockThreshold";s:2:"60";}',
			'phpmyadmin' => 'a:5:{s:12:"hideOtherDBs";s:1:"1";s:9:"uploadDir";s:21:"uploads/tx_phpmyadmin";s:10:"allowedIps";s:0:"";s:12:"useDevIpMask";s:1:"1";s:10:"ajaxEnable";s:1:"0";}',
			'phpunit' => 'a:6:{s:17:"excludeextensions";s:8:"lib, div";s:12:"composerpath";s:0:"";s:13:"selenium_host";s:9:"localhost";s:13:"selenium_port";s:4:"4444";s:16:"selenium_browser";s:8:"*firefox";s:19:"selenium_browserurl";s:0:"";}',
			'realurl' => 'a:5:{s:10:"configFile";s:34:"typo3conf/RealurlConfiguration.php";s:14:"enableAutoConf";s:1:"0";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'rn_base' => 'a:11:{s:13:"verboseMayday";s:1:"0";s:11:"dieOnMayday";s:1:"0";s:21:"forceException4Mayday";s:1:"1";s:16:"exceptionHandler";s:0:"";s:20:"sendEmailOnException";s:19:"example@example.com";s:9:"fromEmail";s:17:"noreply@domain.de";s:24:"send503HeaderOnException";s:1:"1";s:17:"loadHiddenObjects";s:1:"0";s:13:"activateCache";s:1:"0";s:18:"activateSubstCache";s:1:"0";s:8:"debugKey";s:0:"";}',
		),
	),
	'FE' => array(
		'activateContentAdapter' => FALSE,
		'compressionLevel' => 5,
		'debug' => FALSE,
		'lifetime' => '3600',
		'lockIP' => '4',
		'loginSecurityLevel' => 'rsa',
		'noPHPscriptInclude ' => '1',
		'pageNotFoundOnCHashError' => FALSE,
		'pageNotFound_handling' => 'MKTOOLS_TYPOSCRIPT:typo3conf/ext/[projectextension]/Configuration/TypoScript/Extensions/mktools.tss',
		'pageNotFound_handling_statheader' => 'HTTP/1.1 404 Not Found',
		'pageUnavailable_handling' => 'unavailable/',
	),
	'GFX' => array(
		'TTFdpi' => '96',
		'jpg_quality' => '90',
		'png_truecolor' => '1',
	),
	'MAIL' => array(
		'transport' => 'sendmail',
		'transport_sendmail_command' => '/usr/sbin/sendmail -t -i',
	),
	'SYS' => array(
		'UTF8filesystem' => '1',
		'belogErrorReporting' => 0,
		'clearCacheSystem' => FALSE,
		'compat_version' => '6.2',
		'curlUse' => '1',
		'debugExceptionHandler' => 'tx_mktools_util_ExceptionHandler',
		'devIPmask' => 'XXX.XXX.XXX.XXX',
		'displayErrors' => 2,
		'enableDeprecationLog' => FALSE,
		'enable_errorDLOG' => 1,
		'enable_exceptionDLOG' => 1,
		'encryptionKey' => '[REPLACE THIS WITH AN RANDOM 96 SIGN LONG BASE 64 STRING]',
		'errorHandler' => 'tx_mktools_util_ErrorHandler',
		'errorHandlerErrors' => 6135,
		'exceptionalErrors' => 30205,
		'isInitialInstallationInProgress' => FALSE,
		'productionExceptionHandler' => 'tx_mktools_util_ExceptionHandler',
		'reverseProxyHeaderMultiValue' => 'first',
		'sitename' => 'DMK TYPO3',
		'sqlDebug' => 0,
		'syslogErrorReporting' => 0,
		'systemLocale' => 'de_DE.utf8',
		'systemLog' => 'error_log,,2;syslog,LOCAL0,,3',
		'systemLogLevel' => 3,
		't3lib_cs_convMethod' => 'mbstring',
		't3lib_cs_utils' => 'mbstring',
		'useCachingFramework' => 1,
	),
);
?>
